# Generated by Django 2.2 on 2019-05-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(max_length=200, unique=True)),
                ('union_member', models.CharField(blank=True, default='none', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pers_email', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=280)),
            ],
        ),
    ]
